apiVersion: v1
kind: Secret
metadata:
  name: csi-s3-secret
  namespace: yandex-csi-s3
data:
  accessKeyID: WUNBSkV1ZDZ5ckozNC15cXZYTnZDelJ3NA==
  endpoint: aHR0cHM6Ly9zdG9yYWdlLnlhbmRleGNsb3VkLm5ldA==
  secretAccessKey: WUNQSzhqTVJKbUNoV2ZKaDlCTEFaLVlLOHBVMjJrdGZ4VG81LUlxdA==
type: Opaque
