apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: mysqls.otus.homework
spec:
  group: otus.homework
  scope: Namespaced
  names:
    plural: mysqls
    singular: mysql
    kind: MySQL
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          required:
            - spec
          properties:
            spec:
              type: object
              required:
                - image
                - database
                - password
                - storage_size
              properties:
                image:
                  type: string
                  minLength: 1
                  description: Docker image to deploy the MySQL instance
                database:
                  type: string
                  minLength: 1
                  description: Name of the database to create
                password:
                  type: string
                  minLength: 1
                  description: Password for the MySQL root user
                storage_size:
                  type: string
                  pattern: '^[0-9]+Gi$'
                  description: Storage size (e.g., 10Gi, 5Gi)
