apiVersion: v2
name: homework-chart
description: A Helm chart homework for Kubernetes
type: application
version: 0.1.0
appVersion: "1.16.0"

dependencies:
- condition: redis.enabled
  name: redis
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 21.1.6
