apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubernetes-networks
  namespace: argo-cd
spec:
  destination:
    namespace: homework
    server: https://kubernetes.default.svc
  project: otus
  source:
    path: kubernetes-networks
    repoURL: https://github.com/Kuber-2025-04OTUS/i-shulgan_repo.git
    targetRevision: HEAD
