apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: homework
data:
  default.conf: |
    server {
        listen       8000;

        location / {
          root   /homework;
          index  index.html;
        }

        location /healthz {
          return 200 'alive\n';
          add_header Content-Type text/plain;
          access_log off;
        }

    }
