apiVersion: v1
kind: Pod
metadata:
  name: homework-pod
  namespace: homework
spec:
  volumes:
    - name: shared-volume
      emptyDir: {}
    - name: nginx-config
      configMap:
        name: nginx-config
  initContainers:
    - name: init-container
      image: busybox:1.37.0
      command:
        - sh
        - '-c'
        - >-
          echo "<html><body><h1>Hello from $(hostname)!</h1></body></html>" >
          /init/index.html
      volumeMounts:
        - name: shared-volume
          mountPath: /init
  containers:
    - name: web-server
      image: nginx:1.28.0-alpine-slim
      command:
        - nginx
        - '-g'
        - daemon off;
      ports:
        - containerPort: 8000
          protocol: TCP
      volumeMounts:
        - name: shared-volume
          mountPath: /homework
        - name: nginx-config
          mountPath: /etc/nginx/conf.d
      livenessProbe:
        httpGet:
          path: /healthz
          port: 8000
        initialDelaySeconds: 10
        periodSeconds: 30
        failureThreshold: 3
      readinessProbe:
        httpGet:
          path: /ready
          port: 8000
        initialDelaySeconds: 3
        periodSeconds: 10
        failureThreshold: 3
      lifecycle:
        preStop:
          exec:
            command:
              - /bin/sh
              - '-c'
              - rm -f /homework/index.html
